### ISSUE TITLE
(HTML5) HScript doesn't compile correctly

### ISSUE THREAD

**Issue by DotWith** [larsiusprime/polymod#78]
# HScript compiling problems
```
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/graphics/opengl/GLBuffer.hx:16: characters 20-40 : You cannot access the js package while in a macro (for js.html.webgl.Buffer)
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Future.hx:3: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/LimeBackend.hx:35: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:37: characters 29-40 : ... referenced here
```

I tried to fix it by making a haxedef for cpp to allow hscript and polymod. This only got me through a bit more
```js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by DotWith** [comment]
Yes, I've checked my other haxelib imports.

**Comment by DotWith** [comment]
It will work if I only build it, and not test it. I used the **Go Live** plugin on VSCode for the project and it works.

**Comment by Cheemsandfriends** [comment]
> 

The error seems like the thing when you try to test html5 but there's already a "server" running and doesn't let you test it. But really weird

**Comment by MasterEric** [comment]
Pretty sure this is resolved
